name: CI/CD

on:
  push:

permissions:
  contents: none
  id-token: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
    - name: Unit test
      run: npm run test
    - name: e2e test
      run: npm run test:e2e

  CD:
    runs-on: ubuntu-latest
    needs:
      - CI
    environment: Production
    if:
      contains('refs/heads/main', github.ref)
    env:
      GCLOUD_CLOUDRUN_SERVICE: ${{ vars.GCLOUD_CLOUDRUN_SERVICE }}
      GCLOUD_PROJECT_ID: ${{ vars.GCLOUD_PROJECT_ID }}
      GCLOUD_REGION: ${{ vars.GCLOUD_REGION }}
      GCLOUD_IDENTITY_PROVIDER: projects/524340436549/locations/global/workloadIdentityPools/pct-github-action-provider-pool/providers/pct-github-action-provider
      GCLOUD_SERVICE_ACCOUNT: pct-github-action@test-cloud-run-380202.iam.gserviceaccount.com
    steps:
      - uses: actions/checkout@v3
      - uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ env.GCLOUD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCLOUD_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ env.GCLOUD_PROJECT_ID }}/${{ env.GCLOUD_CLOUDRUN_SERVICE }}:${{  github.sha }} .
          docker push gcr.io/${{ env.GCLOUD_PROJECT_ID }}/${{ env.GCLOUD_CLOUDRUN_SERVICE }}:${{  github.sha }}
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.GCLOUD_CLOUDRUN_SERVICE }} \
            --region ${{ env.GCLOUD_REGION }} \
            --image gcr.io/${{ env.GCLOUD_PROJECT_ID }}/${{ env.GCLOUD_CLOUDRUN_SERVICE }}:${{  github.sha }} \
            --platform "managed" \
            --quiet \
            --allow-unauthenticated
      - name: 'Use output'
        run: echo "${{ steps.deploy.outputs.url }}"
